<!--PAGE LANGUAGE:  ENGLISH
Content Page template: v.1.0.1-->
  
<!-- TRANSLATORS:   Look for untranslated text inside HTML tags.  In other words <a tag>any content text between markers like these</a tag>.  Don't worry about translating these comments.  Be sure NOT to translate english page names, file names, div names, div class names, or html syntax.-->
 
<?php require_once ("includes/brikcoins-inc.php");?>

<!--Once translation is completed, you can remove the line below to take the translation notice off the page-->
<?php require_once ("translate-please.php");?>

<!--PAGE BANNER-->

	
<div id="splash-content-block">
	<div id="splash-box">
		<div class="splash-heading">Brikcoins</div>
		<div class="splash-sub">A manual proof-of-value blockchain based on the sequestration of plastic from the biosphere.</div>
		<img src="webp/brikcoins-450px.webp">
	</div>
	
</div>
<div id="splash-bar"></div>

<!-- PAGE CONTENT-->

<a name="top"></a>
<div id="main-content">
<!-- The flexible grid (content) -->
	<div class="row">
		<div class="main">

		<div class="lead-page-paragraph">				
		<p>Based on real world ecological value, the Brikcoin blockchain provides a path towards petro-capital transition.</p>
		</div>

		<div class="page-paragraph">

            <p>Blockchain innovations have enabled a revolution in digital currencies. However, the increasing computational work required to power them has resulted in higher and higher energy demands— all without generating any underlying value.</p>


			<p>In contrast, Brikcoins (BRK / β)) are generated by a proof-of-value manual blockchain that is powered by human work and based on real world value.</p>

			<p>In the same way that ancient currencies were based on the value of their gold and silver coins, Brikcoins are based on the ecological value that they represent.  More than just numbers in ledger, every Brikcoin is underpinned by plastic that has been removed from polluting the biosphere and removed from industries that pollute.</p>
			</p>
         

        </div>

		
			<a name="ECO-VALUE"></a>
            <div class="reg-content-block" id="block1">

                <div class="opener-header">
                    
                    <div class="opener-header-text">
                    <h4>Ecological Value</h4>
                    <h5>In following the Earth's example of carbon care we can generate authentic ecological value.</h5>   
                    <br>
                    </div>

                    <button onclick="preclosed1()" class="block-toggle" id="block-toggle-show1">+</button>
                </div>

                <div id="preclosed1">

                <div class="row">
						<div class="main2">

                		<p>Two billion years ago, the Earth's atmosphere was full of carbon dioxide.  The planet's climate was unstable and its surface barren.  However, steadily the atmosphere's carbon was cycled into carbon-based life.  Over time, as plants and animals lived and died, their fallen biomass was buried.  Steadily more and more carbon ended up in the ground.  With less and less CO2 in the atmosphere, the climate stabilized and the Earth's biosphere greened.</p>

						</div>
						<div class="side2"><img src="webp/earthen-400px.webp" width="80%">
						</div>
					</div>
					<div class="row2">
						<div class="main3">
						<p>Today, our petroleum based plastic comes directly from these ancient underground carbon stores.</p>
						</div>
						<div class="side3"><img src="pngs/albatross-blue-sky.gif" width="150px">
						</div>
					</div>
							
						<p>By managing our plastic in the same way that the Earth cared for its carbon, we can be of ecological service. In particular, by making sure our carbon-plastic does not scatter into the biosphere or atmosphere.</p>
						
						<p>This means ensuring our plastic is not dumped, incinerated or processed by industry.</p>

						<p>Afterall, when plastic is dumped, it degrades into dangerous micro-plastics.  When plastic is incinerated it returns to the atmosphere as CO2.  And when plastic that is processed by industry it causes factories to spin and churn, resulting in more emissions and more plastic products.</p>

						<p>In other words: there is great ecological value in simply securing plastic out of these routes!</p>
						
						<p>The process of securing our plastic out of these routes, is known as plastic sequestration.  Plastic sequestration is define as manual, net-zero, non-industrial process.  Plastic is only sequestered however, when the resulting secured-plastic furthers non-profit applications that benefit humans and support biodiversity.</p> 

						<p>One of the most universal and accessible means of plastic sequestration is ecobricking.</p>
						
						<p>Ecobricked plastic, <i>if it meets the criteria of plastic sequestration</i>, emobodies an ecological value.  This value can be quantified by the weight of plastic sequestered within it.</p>

						<p>Brikcoins are based on the ecological value of authenticated ecobrick sequestered plastic.</p>

						<br><br>
					<h5>ℹ️ Learn more about <a href="sequest.php">GEA criteria for plastic sequestration.</a></h5>

					<h5>ℹ️ Learn more about <a href="/plastic">the Earth's example.</a></h5>

					<h5>ℹ️ View the wikipedia article on <a href="https://en.wikipedia.org/wiki/Plastic_sequestration">Plastic Sequestration.</a></h5>

					<h5>ℹ️ Read about the philosophy of following <a href="https://earthen.io/imagine/">the Earth's example.</a></h5>
				
                </div>
            </div>


			<a name="PROOF-OF-VALUE"></a>
            <div class="reg-content-block" id="block2">

                <div class="opener-header">
                    
                    <div class="opener-header-text">
						<h4>Proof of Value</h4>
						<h5>Brikcoins are generated through the manual process of authenticating ecobrick sequestered plastic.</h5>   
						<br>
                    </div>

                    <button onclick="preclosed2()" class="block-toggle" id="block-toggle-show2">+</button>
                </div>

                <div id="preclosed2">

               		 <div class="row">
						<div class="main2">

						<p>Many cryptocurrencies rely on valueless, computer driven work to establish their generation of coins and the authentication of their ledger (i.e. proof of work).  Often this work results in the consumption of significant amounts of energy and the generation of ewaste that have a negative ecological impact.</p>
						
						<p>In contrast the Brikcoin blockchain is powered by human work and a process of human validation to prove that positive ecological impacts have been acheived.</p>

							<!--<p>Traditional 'proof of work' crypto currencies are based proving on work has been done.  Alas, this computational 'work' has no intrinsic value.  In fact, many critiques argue that the energy and hardware required, has a negative ecological value from the emissions and ewaste that result.  Proof of stake currencies, though they are not directly based upon computational work, nonetheless have the same net-negative ecological impact.</p>-->

						</div>
						<div class="side2"><img src="webp/2-brikcoins-450px.webp" width="90%">
						</div>
					</div>
					<div class="row2">
						<div class="main3">
							<p>The first part of this human labour is the process of ecobricking.  Making an ecobrick is a time consuming manual process.<p>
						</div>
						<div class="side3"><img src="webp/2-brikcoins-450px.webp" width="150px">
						</div>
					</div>
						
					<div class="row">
						<div class="main2">

							<p>Once complete, ecobricks are logged on to the system.  There, rather than rely on computational and crypotographic means of authentication, the Brikcoin blockchain operates on further manual human work.  The authenticatin process of every ecobrick logged involves the review of three independent human inspections.  Only when the reviews of all three validators is positive, does an ecobrick and its plastic become authenticated.</p>

						</div>
						<div class="side2"><img src="pngs/authenticated-ecobrick.png" width="85%">
						</div>
					</div>
					
					<div class="row2">
						<div class="main3">

						<p>In this way, the Brikcoin blockchain is based on a proof that ecological value has been acheived.  In particular through the validation of ecobricks that have been logged from around the world, to "prove" whether the plastic they contain has been sequestered.</p>
						
						<p>In this way, Brikcoins avoid another pitfall of current blochain currencies.  Rather than favor those who currency to invtest, as a non-capital, manual and community powered process, Brikcoins favors anyone anywhere willing to work with their hands to make a meaningful ecological contribution.</p>
						</div>

						<div class="side3"><img src="pngs/authenticated-ecobrick.png" width="150px"></div>
					</div>
				</div>
			</div>
            

			<a name="MANUAL"></a>
            <div class="reg-content-block" id="block3">

                <div class="opener-header">
                    
                    <div class="opener-header-text">
                    <h4>How it works</h4>
                    <h5>Brikcoins are generated and verified by human labour.</h5>   
                    <br>
                    </div>

                    <button onclick="preclosed3()" class="block-toggle" id="block-toggle-show3">+</button>
                </div>

                <div id="preclosed3">

					<br>
					<img src="pngs/manual-blockchain.png" width="90%" loading="lazy" alt="manual proof of value block chain">

					

					<p><b>Step 1: Ecobricking</b></p>

					<p>The brikcoin blockchain revolves around the ecobricking of used plastic.  <a href="what">Ecobricking</a> is an established means of securing plastic. It is a time-consuming, labor-intensive process that is most effectively done manually.  If done <a href="/how">properly</a> an ecobrick can be used for long-term <a href="build">building applications</a>; ensuring that its plastic is secured from industrial processing and release into the biosphere.</p>

					<p>Once complete, ecobrickers log their ecobrick on the <a href="/gobrik">GoBrik</a> platform.  A serial number is given by the system and the ecobrickers enscribes this permanently on the ecobrick. A photo of the ecobrick with the serial number is taken and the logging completed.<p>
					
					<p>The logged ecobrick is then automatically queued for review.  The ecobricker is awarded credits that allow them to validate other ecobricks that have been logged.</p>

					<br><br>
					<p><b>Step 2: Validation</b></p>

					<p>The GEA has defined standards for an ecobrick. Only when a packed bottle meets these standards is it considered an ecobrick, and only then is the plastic it contains considered sequestered.</p> 

					<p>Using one validation credit, ecobrickers are entitled to validate one ecobrick from the queue. The validator proceeds through a three step process of reviewing ecobrick, to ensure that it meets the criteria and standards of plastic sequestration. In total, each ecobrick is reviewed by three validators in the community.</p>
					
					<br><br>
					<p><b>Step 3: Authentication</b></p>

					<p>An algorithm calculates a validation score based on the review. The three validation scores are averaged and if the average exceeds the minimum threshold, the ecobrick is authenticated. Brikcoins are then generated and issued to the validators and the <a href="https://gobrik.com/#cr">GoBrik Central Reserve</a> based on the weight of the ecobrick.</p>

					<p>The amount of Brikcoins generated is a function of the weight of the authenticated ecobricked plastic.  This 'plastic standard' is pegged to a ratio of 1 BRK (ß) to 100g of AES plastic. For example, a 322g ecobrick will generate 3.22 ß, while a 0.41 kg ecobrick will generate 4.10 ß.</p>
					<br><br>

                </div>
            </div>






			<a name="CENTRALIZED"></a>
            <div class="reg-content-block" id="block4">

                <div class="opener-header">
                    
                    <div class="opener-header-text">
                    <h4>Centralized Decentralization</h4>
                    <h5>The Brikcoin blockchain is presided over by the Global Ecobrick Alliance</h5>   
                    <br>
                    </div>

                    <button onclick="preclosed4()" class="block-toggle" id="block-toggle-show4">+</button>
                </div>

                <div id="preclosed4">

					<div class="row">
						<div class="main2">

							<p>The Brikcoin blockchain is developed and maintained by the Global Ecobrick Alliance.  The GEA does so in pursuit of its mission and vision of plastic transition. As a not-for profit Earth Enterprise, the GEA is guided by a mandate of acheiving net-green ecological impacts and redistributing excess revenue back to the global ecobrick movement.</p>
						</div>
						
						<div class="side2">
							<img src="webp/gea-logo-400px.webp" width="80%">
						</div>
					</div>
					
					<div class="row2">
						<div class="main3">
							<p>Through a combination of enterprise structure and server infrastructure, we aim to minimize our grey ecological impacts and maximize of our collective green impact.</p>
						</div>
						<div class="side3"><img src="webp/gea-logo-400px.webp" width="130px">
						</div>
					</div>
								
					<p>The Brikcoin blockchain is permissionless, meaning that its ledger is centralized on GEA managed databases. This structure was elected to minimize the impact of the servers supporting the blockchain, while at the same time maximize the blockchain's empowerment of the decentralized global ecobrick movement.</p>
				</div>
			</div>

			


			<a name="WHITEPAPER"></a>
            <div class="reg-content-block" id="block5">

                <div class="opener-header">
                    
                    <div class="opener-header-text">
                    <h4>White Paper</h4>
                    <h5>The Commodification of Sequestered Plastic</h5>   
                    <br>
                    </div>

                    <button onclick="preclosed5()" class="block-toggle" id="block-toggle-show5">+</button>
                </div>

                <div id="preclosed5">

				<div class="row">
						<div class="main2">

                		<p><p>On Earthday 2020, the GEA released version 1.0 of the Ecobricks & Brikcoin Whitepaper, on The Commodiciation of Manually Sequestered Plastic.  The 32 page document is the work of half a dozen contributors specializing in fields ranging from micro-plastic research, alternative currencies, philosophy, community development and database development.</p>
						<p>The white paper lays out the framework for basing a currency on the ecological value of plastic sequestration.</p>

						</div>
						<div class="side2"><img src="pngs/White-Paper-Icon2-400px.png" width="100%">
						</div>
					</div>
					<div class="row2">
						<div class="main3">
						<p>📥 Download: <a href="https://files.ecobricks.org/s/pC52memM4S2a6LX" target="_blank">The Commodification of Sequestered Plastic</a><br><h5>📄 GEA White Paper | PDF | 2.1 MB</a></p>
						
						</div>
						<div class="side3"><img src="pngs/White-Paper-Icon2-400px.png" width="150px">
						</div>
					</div>
				 
					<p>The white paper is updated as of March 2022 to reflect three years of beta-usage by our 50,000 gobrik users, over 150,000 ecobricks and a pool of over 250,000 ß (as of March, 2022).</p><br>

                </div>
            </div>



			<div class="page-paragraph-reg">
                 
                 <div class="row">
                
                    <div class="main2">
                         <br><br>
						 <h3>The Brikchain</h3>
                        
                         <p>The proof-of-value manual blockchain that powers Brikcoins is affectionately know as the <a href="brikchain.php">the brikchain</a> it is the full ledger of transactions generated by the authentication of ecobricked plastic around on the world on the GoBrik platform.  GoBrik and the Brikchain are maintained and developed by the Global Ecobrick Alliance as a for-Earth, non-profit enterprise.</p>

						<p>As a non-capital, manual process, Brikcoins favors anyone anywhere willing to work with their hands to make a meaningful ecological contribution.</p>
						<br><br>
						<a class="action-btn" href="brikchain.php">🔎 Browse the Brikchain</a>
						<p style="font-size: 0.85em; margin-top:20px;">The live chain of transactions and ecobricks.</a></p>
                    
                    </div>

                    <div class="side2">
                        <br><img src="webp/brk-cascade.webp" width="90%" alt="brikcoins in action" loading="lazy">
                    </div>
                </div>
            </div>


		</DIV>
		

		<div class="side">

		<div id="side-module-desktop-mobile">
				<img src="webp/earthen-story-400px.webp" width="90%" alt="Following the Earth's example through eco bricking">
				<br><h4>Following the Earth's Example</h4>
				<h5>Plastic Sequestration follows the Earth’s example.  Learn about the ancient history of this modern methodology.</h5><br>
				<a class="module-btn" href="/plastic">Plastic's Long Story</a>
                <br>
			</div>   
         

			<div id="side-module-desktop-mobile">
				<img src="webp/earthhome-400px.webp" width="100%" loading="lazy" alt="eco brik and earth building can make regenerative structures">
				<h4>Plastic Transition</h4>
				<h5>Brikcoins aspire to accelerate petro-capital transition. Rather than see plastic as ‘waste’ we see it's sequestration as the value to base Brikcoins'.</h5><br>
				<a class="module-btn" href="transition.php">Learn More</a>
			</div>

            <div id="side-module-desktop-mobile">
				<img src="webp/earthen-500px.webp" width="80%" alt="For-Earth Enterprise through eco bricking">
				<h4>Earthen Ethics</h4>
				<h5>Brikcoins are based on the value generated by following the Earth's example of ecological enrichment.</h5><br>
				<a class="module-btn" href="https://medium.com/earthen/the-six-earthen-ways-1b2db3d2b27" target="_blank">Learn More</a>
			</div>

			<div id="side-module-desktop-mobile">
					<img src="webp/gea-logo-400px.webp" width="90%" alt="The Global Eco Brick Alliance">
					<h4>Global Ecobrick Alliance</h4>
					<h5>The GEA is dedicated to accelerating plastic transition.  	We preside over the GoBrik platform and the Brikcoin blockchain.</h5><br>
					
				</div>



		</div>

	</div>
</div>



	<!--FOOTER STARTS HERE-->

	<?php require_once ("footers/footer-$lang.php");?>


<!-- CUSTOM PAGE SCRIPTS-->

<!-- This script is for pages that use the accordion content system-->
<script src="accordion-scripts.js" defer></script>


</div>
</body>
</html>



