
<!--PAGE LANGUAGE:  ENGLISH
Special Ecobrick View Page: v.1.0.1-->
  
 
<?php 

require_once ("includes/details-ecobrick-page-inc.php");




echo '

</head>

<BODY id="full-page">

	  <div id="load-background">';


require_once ("menus/menu-$lang.php");

require_once ("translate-please.php");

echo '<div class="splash-content-block">
		<div class="splash-box">
			<div class="splash-heading">';
				

			?>

		
		<div class="side">

		<div id="side-module-desktop-mobile">
				<img src="webp/eb-sky-400px.webp" width="90%" alt="Following the Earth's example through eco bricking">
				<br><h4>Learn about Ecobricks</h4>
				<h5>Ecobricks are a simple solution for managing our plastic.</h5><br>
				<a class="module-btn" href="/abouot">About Ecobricks</a>
                <br>
			</div>   
         

			<div id="side-module-desktop-mobile">
				<img src="webp/tens-thousands.webp" width="100%" loading="lazy" alt="eco brik and earth building can make regenerative structures">
				<h4>Plastic Transition</h4>
				<h5>Brikcoins aspire to accelerate petro-capital transition. Rather than see plastic as ‘waste’ we see it's sequestration as the value to base Brikcoins'.</h5><br>
				<a class="module-btn" href="transition.php">Learn More</a>
			</div>

            <div id="side-module-desktop-mobile">
				<img src="webp/earthen-500px.webp" width="80%" alt="For-Earth Enterprise through eco bricking">
				<h4>Earthen Ethics</h4>
				<h5>Brikcoins are based on the value generated by following the Earth's example of ecological enrichment.</h5><br>
				<a class="module-btn" href="https://earthen.io/imagine/" target="_blank">Learn More</a>
			</div>

			<div id="side-module-desktop-mobile">
					<img src="/webp/for-earth500px.webp" width="90%" alt="For-Earth Enterprise">
					<h4>Global Ecobrick Alliance</h4>
					<h5>The GEA is dedicated to accelerating plastic transition.  	We preside over the GoBrik platform and the Brikcoin blockchain.</h5><br>
					
				</div>



		</div>

	</div>
</div>



	<!--FOOTER STARTS HERE-->

	<?php require_once ("footers/footer-$lang.php");?>


<!-- CUSTOM PAGE SCRIPTS-->

<!-- This script is for pages that use the accordion content system-->
<script src="accordion-scripts.js" defer></script>


</div>
</body>
</html>