---
deployment:
  tasks:

    # 1) Define where the live site lives
    - export WEBROOT=/home/ecobricks/public_html

    # 3) Copy master English files into each translated folder
    - /usr/bin/install -m 644 en/what.php $WEBROOT/zh/what.php
    - /usr/bin/install -m 644 en/what.php $WEBROOT/es/what.php
    - /usr/bin/install -m 644 en/what.php $WEBROOT/fr/what.php
    - /usr/bin/install -m 644 en/what.php $WEBROOT/id/what.php

    - /usr/bin/install -m 644 en/plastic.php $WEBROOT/zh/plastic.php
    - /usr/bin/install -m 644 en/plastic.php $WEBROOT/es/plastic.php
    - /usr/bin/install -m 644 en/plastic.php $WEBROOT/fr/plastic.php
    - /usr/bin/install -m 644 en/plastic.php $WEBROOT/id/plastic.php

    - /usr/bin/install -m 644 en/media.php $WEBROOT/zh/media.php

    - /usr/bin/install -m 644 en/index.php $WEBROOT/zh/index.php
    - /usr/bin/install -m 644 en/index.php $WEBROOT/es/index.php
    - /usr/bin/install -m 644 en/index.php $WEBROOT/fr/index.php
    - /usr/bin/install -m 644 en/index.php $WEBROOT/id/index.php

    # 4) Copy side-modules (individual files)
    - /usr/bin/install -m 644 en/side-modules/sequest-module.php $WEBROOT/zh/side-modules/sequest-module.php
    - /usr/bin/install -m 644 en/side-modules/signup-now.php $WEBROOT/zh/side-modules/signup-now.php
    - /usr/bin/install -m 644 en/side-modules/transition-module.php $WEBROOT/zh/side-modules/transition-module.php
    - /usr/bin/install -m 644 en/side-modules/earthen-ethics.php $WEBROOT/zh/side-modules/earthen-ethics.php
