---
deployment:
  tasks:

    # 1) Define where the live site lives
    - export WEBROOT=/home/ecobricks/public_html

    # 2) Make sure the zh directory exists
    - /bin/mkdir -p $WEBROOT/zh

    # 3) Copy—or overwrite—the master English file into the Chinese folder
    #    -m 644 keeps sensible permissions (read-only for world)
    #    The install command creates the file if it doesn’t exist.
    - /usr/bin/install -m 644 en/what.php $WEBROOT/zh/what.php
    - /usr/bin/install -m 644 en/index.php $WEBROOT/zh/index.php
