---
deployment:
  tasks:

    # 1) Define where the live site lives
    - export WEBROOT=/home/ecobricks/public_html

    # 3) Copy master English files into each translated folder
    - /usr/bin/install -m 644 en/what.php $WEBROOT/zh/what.php
    - /usr/bin/install -m 644 en/what.php $WEBROOT/es/what.php
    - /usr/bin/install -m 644 en/what.php $WEBROOT/fr/what.php
    - /usr/bin/install -m 644 en/what.php $WEBROOT/id/what.php

    - /usr/bin/install -m 644 en/plastic.php $WEBROOT/zh/plastic.php

