	

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.4/css/jquery.dataTables.css">
  
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.4/js/jquery.dataTables.js"></script>

<script>

$(document).ready(function() {
    $('#brikchain').DataTable( {
		"processing": true,
        "serverSide": true,
		"ajax": "ajax.php"

    } );
} );

</script>
<script>

$(document).ready(function() {
    $('#ecobricks').DataTable( {
		"processing": true,
        "serverSide": true,
		"ajax": "ajax-ecobricks.php"

    } );
} );

</script>

<style>
#brikchain {
  font-family: 'Mulish', Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
  font-weight: 300;
}

#brikchain td, #brikchain th {
  border: 1px solid #ddd;
  padding: 8px;
}

#brikchain tr:nth-child(even){background-color: #f2f2f2;}

#brikchain tr:hover {background-color: #ddd;}

#brikchain th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #E39009;
  color: white;
}
</style>

<style>
#ecobricks {
  font-family: 'Mulish', Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
  font-weight: 300;
}

#ecobricks td, #ecobricks th {
  border: 1px solid #ddd;
  padding: 8px;
}

#ecobricks tr:nth-child(even){background-color: #f2f2f2;}

#ecobricks tr:hover {background-color: #ddd;}

#ecobricks th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #E39009;
  color: white;
}
</style>

</head>
							  										  
<BODY id="full-page">

	<div id="load-background">

<a name="top"></a>

<div id="main-content">
<!-- The flexible grid (content) -->
			<div class="lead-page-paragraph">
				<br><br>
				<p>Ecobrick Detail Page</p>
			</div>
			<div class="page-paragraph">
				<p>An overview of the ecobrick generated by the ecobricker and recorded for that brik.</a>.</p>
			</div>
			<hr>
            <div class="page-paragraph">
<!-- The DB connection creator -->
<?php include 'db.php';?>

<?php

// Get the contents from the Ecobrick table as an ordered View, using the serial_no from the URL.
$serialNo = $_GET['serial_no'];

// Refered to  https://www.w3schools.com/php/php_mysql_select_where.asp1
$sql = "SELECT * FROM tb_ecobricks WHERE serial_no = " . $serialNo;

$result = $conn->query($sql);
if ($result->num_rows > 0) {
	echo "<h1> Use Serial Number from URL => " . $serialNo ."</h1>";
    //  Output data of each row
    while($array = $result->fetch_assoc()) {

		echo "</br><h3>Ecobrick Serial No: <var>" . $array["serial_no"] ."</var></h3> </br>";
		echo " <p>Owner: <var>" . $array["owner"] ."</var> </p>" ;
		echo " <p>Volume: <var>" . $array["volume_ml"] ."&#8202;ml</p>" ;
		echo " <p>Weight: <var>" . $array["weight_g"] ."&#8202;g</var></p>" ;
		echo " <p>Density: <var>" . $array["density"] ."</var></p>" ;
		echo " <p>Dated: <var>" . $array["date_logged_ts"] ."</var></p>" ;
		echo " <p>CO2e = <var>" . $array["CO2_kg"] ."&#8202;kg</var></p>" ;
		echo " <p>Sequestration type: <var>" . $array["sequestration_type"]."</var></p>" ;
		echo " <p>Last validation time = " . $array["last_validation_ts"] ."</var><p>" ;
		echo " <p>Validator 1: <var>" . $array["validator_1"] ."</var> </p>" ;
		echo " <p>Validator 2: <var>" . $array["validator_2"] ."</var> </p>" ;
		echo " <p>Validator 3: <var>" . $array["validator_3"] ."</var> </p>" ;
		echo " <p>Validation score avg: <var>" . $array["validation_score_avg"] ."</var></p>" ;
		echo " <p>Last ownership change: " . $array["last_ownership_change"] ."</var></p>" ;
		echo " Final validation score = " . $array["final_validation_score"] ."</br>" ;
		echo " Weight authenticated = " . $array["weight_authenticated_kg"] ."kg</br>" ;
		echo " Country = <var>" . $array["location_country"] ."</var></br>" ;
		echo " Region = <var>" . $array["location_region"] ."</var></br>" ;
		echo " City = <var>" . $array["location_city"] ."</var></br>" ;
		echo " Full location = <var>" . $array["location_full"] ."</var></br>" ;
		echo " Community = <var>" . $array["community_name"] ."</var></br>" ;
		echo " Brand  = <var>" . $array["brand_name"] ."</var></br>" ;
		echo " Bottom colour = <var>" . $array["bottom_colour"] ."</var></br>" ;
		echo " <p>Plastic from  = <var>" . $array["plastic_from"] ."</var></p></br>" ;
		echo " <p>Display value = " . $array["ecobrick_brk_display_value"] ."</p></br>" ;
		echo " <p>Brikcoin amount = " . $array["ecobrick_brk_amt"] ."&#8202;ß</p></br>" ;
		
    }
} else {
    echo "No results found for selected ecobrick serial number";
}
$conn->close();

?>
	
	<br><br>

</div>

	<!--FOOTER STARTS HERE-->

	<?php include 'footer.php'; ?>

	<!--FOOTER ENDS HERE-->
</div>
</body>
</html>