<!-- This calls GEA typography -->

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

<!-- Mulish loads first for first page view-->

<link href="https://fonts.googleapis.com/css2?family=Mulish:wght@300;500&display=swap" rel="stylesheet" media="print" onload="this.media='all'">

<!-- Arvo loads very last to speed up first load.  See the script in the footer that triggers this  -->

<noscript>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css2?family=Arvo&display=swap" />
</noscript>

<!-- This calls our Github hosted stylesheet - if it gets hopelessly cached and doesn't load, up the version number! -->

<link rel="stylesheet" type="text/css" href="stylesheet-general.css?v0.14">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>


</head>




<BODY id="full-page">

<div id="load-background">

    <a name="top"></a>

    <div id="main-content">

        <div class="page-paragraph">
            <p>An overview of the ecobrick generated by the ecobricker and recorded for that brik.</a>.</p>


            <!-- The DB connection creator -->
            <?php include 'db.php';?>

            <?php

            // Get the contents from the Cash Transaction table as an ordered View, using the trans_id from the URL.
            $cashTranId = $_GET['cash_tran_id'];

            // Refered to  https://www.w3schools.com/php/php_mysql_select_where.asp1
            $sql = "SELECT * FROM vw_cash_tran_desc WHERE cash_tran_id = " . $cashTranId;

            $result = $conn->query($sql);
            if ($result->num_rows > 0) {

                //  echo "<h1> Use Serial Number from URL => " . $serialNo ."</h1>"; Output data of each row
                while($array = $result->fetch_assoc()) {

                    echo '<img src="'. $array["ecobrick_full_photo_url"] .'" width="500" alt="Ecobrick basic pic"/>';
                    echo "</br><h3>Cash transaction id: <var>" . $array["cash_tran_id"] ."</var></h3> </br>";
                    echo " <div class=\"general-field\"><b>Sender ecobricker:</b> <var>" . $array["sender_ecobricker"] . "</var></div>" ;
                    echo " <div class=\"general-field\"><b>Sender ecobricker:</b> <var><i>" . $array["sender_ecobricker"] ."</i></var> </div>" ;
                    echo " <div class=\"general-field\"><b>Datetime sent:</b> <var>" . $array["datetime_sent_ts"] ."</var></div>" ;
                    echo " <div class=\"general-field\"><b>Type of transaction:</b> <var>" . $array["sequestration_type"]."</var></div>" ;
                    echo " <div class=\"general-field\"><b>Transaction name:</b> " . $array["tran_name_desc"] ."</var></div>" ;
                    echo " <div class=\"general-field\"><b>Native ccy amt</b> <var>" . $array["native_ccy_amt"] ."</var> </div>" ;
                    echo " <div class=\"general-field\"><b>Currency code:</b><var> " . $array["currency_code"] ."</var></div>" ;
                    echo " <div class=\"general-field\"><b>Exchange ratio</b> <var>" . $array["exchange_ratio"] ."</var> </div>" ;
                    echo " <div class=\"general-field\"><b>Total product cost incl shipping:</b> <var>" . $array["total_product_cost_incl_shipping"] ."</var> </div>" ;
                    echo " <div class=\"general-field\"><b>Product</b> <var>" . $array["product"] ."</var></div>" ;
                    echo " <div class=\"general-field\"><b>Product cost:</b> <var>" . $array["product_cost"] ."</var></div>" ;
                    echo " <div class=\"general-field\"><b>Transaction date:</b> <var>" . $array["transaction_date_dt"] ."</var></div>" ;
                    echo " <div class=\"general-field\"><b>Total product cost+ccy display:</b> <var> " . $array["total_product_cost_+ccy_display"] ."&#8202;kg</var></div>" ;
                    echo " <div class=\"general-field\"><b>Receiving gea acct</b> " . $array["location_country"] ."</div>" ;
                    echo " <div class=\"general-field\"><b>Sender for display</b> <var>" . $array["sender_for_display"] ."</var></div>" ;
                    echo " <div class=\"general-field\"><b>Receiver for display:</b> <var>" . $array["receiver_for_display"] ."</var></div>" ;
                    echo " <div class=\"general-field\"><b>Purchase method</b> <var>" . $array["purchase_method"] ."</var></div>" ;
                    echo " <div class=\"general-field\"><b>Paymentt record:</b> <var>" . $array["paymt_record_url"] ."</var></div>" ;
                }
            } else {
                echo "No results found for selected ecobrick serial number";
            }
            $conn->close();

            ?>

            <br><br>

        </div>

    </div>
</body>
</html>
