<div class="side-module-desktop-mobile">
				<img src="../icons/earthen-ethics-icon-ecobricks-org.svg" width="80%" alt="For-Earth Enterprise through eco bricking">
				<h4>Earthen Ethics</h4>
				<h5>Brikcoins are based on the value generated by following Earth's example of carbon concentration and ecological enrichment.</h5><br>
				<a class="module-btn" href="principles.php" >Learn More</a>
			</div>
