/*-----------------------------------

FRENCH SNIPPETS FOR ECOBRICKS.ORG -- story.php


-----------------------------------*/


// Ampersand (&): Should be escaped as &amp; because it starts HTML character references.
// Less-than (<): Should be escaped as &lt; because it starts an HTML tag.
// Greater-than (>): Should be escaped as &gt; because it ends an HTML tag.
// Double quote ("): Should be escaped as &quot; when inside attribute values.
// Single quote/apostrophe ('): Should be escaped as &#39; or &apos; when inside attribute values.
// Backslash (\): Should be escaped as \\ in JavaScript strings to prevent ending the string prematurely.
// Forward slash (/): Should be escaped as \/ in </script> tags to prevent prematurely closing a script.


const fr_Page_Translations = {

    '001-splash-title': 'Notre Histoire',
    '002-splash-subtitle': "L'Alliance Globale d'Écobriques est enracinée dans la terre et la tradition de sagesse des Igorots du nord de Luzon",
    '003-splash-image-alt': '<img alt="La communauté mondiale des écobriques" src="../pngs/community.png" style="width: 85%"/>',
    '005-first-page-paragraph': "La GEA est née dans la vallée verdoyante de la rivière Chico, sur le territoire traditionnel du peuple Igorot (<i>Kaigorotan</i>) des Cordillères du nord des Philippines. Guidés par leur éthos <a href=\"/ayyew\">Ayyew</a> et leurs principes régénératifs, nous nous sommes convaincus que résoudre véritablement le problème du plastique nécessite une relation nouvelle et prudente avec l'économie pétro-capitaliste. Nous avons donc établi la GEA comme une <a href=\"about.php#block2\">Entreprise Terrestre</a> à but non lucratif&mdash; libre de maintenir des standards mondiaux pour l'écobriquage et la séquestration du plastique sans motif de profit, et entièrement concentrée sur le service à la Terre.",
    '007-gea-intro-image-alt': "Le logo mandalique de l'Alliance Globale d'Écobriques",
    '007-gea-intro-text': "L'Alliance Globale d'Écobriques se consacre à la transition plastique depuis plus d'une décennie. Nous le faisons à travers la diffusion mandalique de principes et de pratiques d'écobriquage pour élever la conscience écologique.",
    '007-gea-intro-btn': 'À propos de la GEA',
    '008-block1-header': 'Notre Histoire Épique des Origines',
    '009-block1-subheader': "Comment un voyageur bloqué, une rivière et une communauté de montagne ont déclenché un mouvement mondial.",
    '010-block1-hero-image-alt': 'Rizières en terrasses dans le nord de Luzon',
    '011-block1-hero-caption': "Les rizières en terrasses du nord de Luzon sont entretenues par les Igorots depuis des siècles comme moyen d'autosuffisance alimentaire.",
    '012-block1-main2-p1': "L'Alliance Globale d'Écobriques trouve ses racines dans les montagnes du nord reculé des Philippines. En 2010, lors de vacances qui ont mal tourné, <a href=\"https://www.spot.ph/newsfeatures/newsfeatures-peopleparties/71089/interview-russel-maier-ecobricks-a00171-20170810-lfrm2\" target=\"_blank\" rel=\"noopener\">l'artiste canadien Russell Maier s'est retrouvé bloqué dans un petit village de la vallée de Sabangan</a>, sur la terre du peuple Igorot. Incapable de joindre les deux bouts et de rentrer chez lui, Russell&mdash; un artiste ayant une formation en philosophie&mdash; <a data-lang-id=\"012a-block1-link1\" href=\"https://russs.net/how-i-fucked-up-my-life-and-became-stranded-in-a-remote-tribal-village-for-four-years/\" target=\"_blank\" rel=\"noopener\">a été contraint de s'installer dans les Cordillères pendant cinq ans</a>.",
    '012a-block1-link1': "a été contraint de s'installer dans les Cordillères pendant cinq ans",
    '013-block1-main2-p2': "Vivant dans la communauté, il a commencé à se demander ce qu'il advenait des bouteilles en plastique, des emballages et autres objets qu'il consommait et jetait. En suivant ses voisins alors qu'ils rassemblaient et emportaient les déchets du quartier, il a découvert que son plastique était déversé dans la rivière Chico locale, près de l'endroit où les enfants nageaient et les hommes pêchaient. Troublé par cela, il a commencé à expérimenter le recyclage créatif&mdash; en réaménageant sa maison avec des créations en plastique et en les vendant à l'étranger. Mais une question le hantait: que se passe-t-il quand ces créations en plastique arrivent en fin de vie? Le problème du plastique était-il vraiment résolu?",
    '018-block1-main3-p1': "À cette époque, Russell a été initié au travail d'Andreas Froese, qui remplissait des bouteilles de sable en Amérique Centrale pour fabriquer des &ldquo;bottle bricks&rdquo;. Russell et ses amis sont descendus à la rivière Chico pour essayer la technique. L'endroit où ils ramassaient le sable se trouvait être celui où le plastique local était déversé et brûlé&mdash; alors ils ont improvisé, en emballant un mélange de sable et de plastique dans les bouteilles. Cela fonctionnait tout aussi bien, alors ils ont ajouté de plus en plus de plastique. Avec un mélange de bouteilles&mdash; certaines remplies de sable, d'autres uniquement de plastique&mdash; ils ont construit un petit mur de jardin. Les bouteilles remplies de plastique étaient non seulement tout aussi efficaces, mais avaient l'avantage supplémentaire de sécuriser du plastique qui aurait autrement fini dans la rivière.",
    '021-block1-p1': "Russell a poursuivi l'expérience chez lui, construisant son jardin avec elles. Ses voisins voulaient en savoir plus, alors il a travaillé avec l'école de la ville pour nettoyer un vieux tas de plastique. La nouvelle s'est répandue rapidement, et l'idée a été accueillie avec un enthousiasme débordant&mdash; d'abord dans leur ville, puis dans les villes voisines. Alors que la gestion des déchets plastiques atteignait un point critique à Bontoc, la capitale provinciale, la demande pour une solution accessible a augmenté. Russell et Irene Bakisan ont développé le premier Guide Vision Ecobrick&mdash; une ressource simple et photocopiable distribuée à des centaines d'écoles. En 2014, près de trois mille écoles avaient mis en place le programme d'écobriques dans tout le département de l'Éducation du nord des Philippines.",
    '032-block1-video1-caption': 'Solving Plastic -- one bottle at a time in the Northern Philippines',
    '022-block1-p2': "Le développement des concepts d'écobrique a été profondément influencé par les principes Igorot. Inspirés par un mur en pierre de rizière en terrasse qui s'était effondré lors d'une tempête et avait été reconstruit avec les mêmes pierres, Russell et Irene étaient déterminés à ce que les constructions en écobriques soient elles aussi réutilisables encore et encore. Inspirée par le concept d'<a data-lang-id=\"023-block1-link1\" href=\"/ayyew\">Ayyew</a>, l'équipe a privilégié l'utilisation des écobriques pour construire des espaces verts qui enrichiraient les quartiers et les écoles.",
    '023-block1-link1': 'Ayyew',
    '024-block1-p3': "Avec le lancement d'<a href=\"index.php\">Ecobricks.org</a> en 2013, le mouvement philippin de l'écobriquage a découvert que des gens du monde entier&mdash; en quête désespérée d'une solution simple au plastique&mdash; avaient commencé à écobriquer de façon indépendante. Après avoir pris contact avec des leaders du mouvement en Afrique du Sud et en Amérique du Nord et Centrale, il a été décidé de former une alliance pour établir une cohérence à travers ce mouvement mondial en pleine croissance. Menée par Russell Maier, Jo Stodgel (Upcycle Santa Fe), Candice Mostert, Patricia Acuna et Irene Bakisan, l'Alliance Globale d'Écobriques (GEA) s'est formée aux côtés du Guide Vision Ecobrick v2.0. En 2014, avec le soutien d'Ian Domisse, fondateur de l'Ecobrick Exchange en Afrique du Sud, l'alliance a convenu d'utiliser le terme sans trait d'union et en minuscules <b>&ldquo;ecobrick&rdquo;</b> comme terme standardisé dans tous les supports&mdash; afin que les écobriqueurs partout dans le monde puissent se rallier autour d'un seul mot, un seul hashtag et un seul terme de recherche.",
    '033-block1-video2-caption': 'Seni Mengolah Sampah Plastik &ndash; Insight with Desi Anwar',
    '025-block1-p4': "Début 2015, Russell a déménagé en Indonésie et, avec l'aide de Nurkinanti Laraskusuma, le Guide Vision Ecobrick a été traduit en indonésien. Fin 2015, Russell Maier et Ani Himawati ont officiellement fondé la GEA en tant qu'Entreprise Terrestre à but non lucratif, avec la mission de soutenir l'infrastructure technologique et philosophique du mouvement mondial de l'écobriquage. <a data-lang-id=\"025c-block1-link3\" href=\"http://jogjatv.tv/pemkot-luncurkan-ecobricks-untuk-atasi-sampah-plastik/\" target=\"_blank\" rel=\"noopener\">En 2016,</a> le mouvement <a data-lang-id=\"025b-block1-link2\" href=\"https://www.youtube.com/watch?v=fK-cc8SfSW8\" target=\"_blank\" rel=\"noopener\">s'est enflammé à Yogyakarta, en Indonésie</a>. Ani Himawati a joué un rôle déterminant dans le développement de la méthodologie de formation de la GEA, en appliquant <a data-lang-id=\"025a-block1-link1\" href=\"https://russs.net/mandalas/\" target=\"_blank\" rel=\"noopener\">les principes de manifestation communautaire mandalique développés par Russell Maier</a>&mdash; une méthodologie qui a depuis porté le mouvement indonésien vers une croissance exponentielle à travers des ateliers de démarrage, des programmes de formation de formateurs et des convergences d'écobriques.",
    '025b-block1-link2': "s'est enflammé à Yogyakarta, en Indonésie",
    '025c-block1-link3': 'En 2016,',
    '025a-block1-link1': 'les principes de manifestation communautaire mandalique développés par Russell Maier',
    '034-block1-p9': "Au fil des années qui ont suivi, le mouvement indonésien de l'écobriquage, en partenariat avec divers gouvernements locaux, des organisations chrétiennes et islamiques, les scouts nationaux et des mouvements écologiques étudiants, a été fait connaître à des dizaines de millions d'Indonésiens à travers l'archipel du pays.",
    '026-block1-p5': "Le mouvement d'écobriquage au Royaume-Uni s'est enflammé peu après la diffusion de Blue Planet II en décembre 2017. En janvier 2018, Mary Bacoo et Lucie Mann ont rejoint la GEA en tant que formatrices depuis le Royaume-Uni. Lucie a lancé la <a data-lang-id=\"026a-block1-link1\" href=\"https://www.facebook.com/groups/ecobricksUK\" target=\"_blank\" rel=\"noopener\">page Facebook Ecobricks UK</a>, qui a décollé en octobre 2018 lorsque des scandales concomitants dans l'industrie britannique du recyclage ont éclaté dans les médias et rendu l'écobriquage viral. En 2019, on comptait plus de 30 formateurs GEA au Royaume-Uni, et le mouvement impliquait des centaines de milliers d'écobriqueurs.",
    '027-block1-quote1': '<i>&ldquo;Nous ne comprenons pas comment cela se produit, mais avec Blue Planet II, le monde s&rsquo;est soudainement électrisé face au crime consistant à jeter du plastique dans l&rsquo;océan.&rdquo;</i>',
    '028-block1-quote1-citation': '&mdash; David Attenborough',
    '029-block1-p6': "Entre 2017 et 2018, des centaines de formateurs ont rejoint le réseau de la GEA à travers les Philippines, l'Indonésie et l'Afrique du Sud grâce à nos <a data-lang-id=\"029a-block1-link1\" href=\"/trainings\">programmes de formation de formateurs</a> en direct et en ligne. En 2018, nos trois premiers formateurs américains&mdash; Sabrina Auclair, Luke Henkel et Jess Beck&mdash; ont rejoint l'équipe.",
    '026a-block1-link1': 'page Facebook Ecobricks UK',
    '029a-block1-link1': 'programmes de formation de formateurs',
    '030-block1-p7': "Fin 2019, l'attention du monde est passée des dangers du plastique à ceux du COVID-19. L'écobriquage a connu un déclin de participation à travers le monde.",
    '031-block1-p8': "Cependant, le plastique n'a pas disparu. Bien au contraire. La consommation de plastique et son rejet dans les écosystèmes locaux se sont accélérés ces dernières années. Lentement mais sûrement, une résurgence de l'écobriquage se répand à nouveau à mesure que les communautés réalisent que la gestion industrielle et corporative du plastique cause plus de problèmes qu'elle n'en résout."

}
