/*-----------------------------------

SPANISH SNIPPETS FOR ECOBRICKS.ORG -- story.php


-----------------------------------*/


// Ampersand (&): Should be escaped as &amp; because it starts HTML character references.
// Less-than (<): Should be escaped as &lt; because it starts an HTML tag.
// Greater-than (>): Should be escaped as &gt; because it ends an HTML tag.
// Double quote ("): Should be escaped as &quot; when inside attribute values.
// Single quote/apostrophe ('): Should be escaped as &#39; or &apos; when inside attribute values.
// Backslash (\): Should be escaped as \\ in JavaScript strings to prevent ending the string prematurely.
// Forward slash (/): Should be escaped as \/ in </script> tags to prevent prematurely closing a script.


const es_Page_Translations = {

    '001-splash-title': 'Nuestra Historia',
    '002-splash-subtitle': 'La Alianza Global de Ecoladrillos está enraizada en la tierra y la tradición de sabiduría de los Igorot del norte de Luzón',
    '003-splash-image-alt': '<img alt="La comunidad global de ecoladrillos" src="../pngs/community.png" style="width: 85%"/>',
    '005-first-page-paragraph': 'La AGE nació en el verde valle del Río Chico, en el territorio tradicional del pueblo Igorot (<i>Kaigorotan</i>) de las Cordilleras del norte de Filipinas. Guiados por su ethos <a href="/ayyew">Ayyew</a> y sus principios regenerativos, nos convencimos de que resolver verdaderamente el problema del plástico requiere una relación nueva y cuidadosa con la economía petro-capital. Así que establecimos la AGE como una <a href="about.php#block2">Empresa Terrestre</a> sin fines de lucro&mdash; libre para mantener estándares globales de ecoladrillado y secuestro de plástico sin motivo de lucro, y en su lugar totalmente enfocada en el servicio a la Tierra.',
    '007-gea-intro-image-alt': 'El logo mandálico de la Alianza Global de Ecoladrillos',
    '007-gea-intro-text': 'La Alianza Global de Ecoladrillos se ha enfocado en la transición plástica durante más de una década. Lo hacemos a través de la diseminación mandálica de ecoladrillado principista y práctico para elevar la conciencia ecológica.',
    '007-gea-intro-btn': 'Sobre la AGE',
    '008-block1-header': 'Nuestra Épica Historia de Origen',
    '009-block1-subheader': 'Cómo un viajero varado, un río y una comunidad de montaña encendieron un movimiento global.',
    '010-block1-hero-image-alt': 'Arrozales en terrazas en el norte de Luzón',
    '011-block1-hero-caption': 'Los arrozales en terrazas del norte de Luzón han sido mantenidos por los Igorot durante siglos como medio de autosuficiencia alimentaria.',
    '012-block1-main2-p1': 'La Alianza Global de Ecoladrillos encuentra sus raíces en las montañas del remoto norte de Filipinas. En 2010, en unas vacaciones que salieron mal, <a href="https://www.spot.ph/newsfeatures/newsfeatures-peopleparties/71089/interview-russel-maier-ecobricks-a00171-20170810-lfrm2" target="_blank" rel="noopener">el artista canadiense Russell Maier quedó varado en un pequeño pueblo del Valle de Sabangan</a>, en la tierra del pueblo Igorot. Incapaz de llegar a fin de mes y regresar a casa, Russell&mdash; un artista con formación en filosofía&mdash; <a data-lang-id="012a-block1-link1" href="https://russs.net/how-i-fucked-up-my-life-and-became-stranded-in-a-remote-tribal-village-for-four-years/" target="_blank" rel="noopener">se vio obligado a establecer su hogar en las Cordilleras durante cinco años</a>.',
    '012a-block1-link1': 'se vio obligado a establecer su hogar en las Cordilleras durante cinco años',
    '013-block1-main2-p2': 'Viviendo en la comunidad, comenzó a preguntarse qué pasaba con las botellas de plástico, el embalaje y otros artículos que consumía y desechaba. Siguiendo a sus vecinos mientras recogían y se llevaban los residuos del vecindario, descubrió que su plástico terminaba en el Río Chico local, cerca de donde los niños nadaban y los hombres pescaban. Perturbado por esto, comenzó a experimentar con el upcycling&mdash; renovando su hogar con creaciones de plástico y vendiéndolas en el extranjero. Pero una pregunta lo perseguía: ¿qué pasa cuando estas creaciones de plástico llegan a su fin? ¿Se estaba realmente resolviendo el problema del plástico?',
    '018-block1-main3-p1': 'Por esta época, Russell fue introducido al trabajo de Andreas Froese, quien había estado llenando botellas con arena en Centroamérica para hacer &ldquo;bottle bricks&rdquo;. Russell y sus amigos bajaron al Río Chico para probar la técnica. El lugar donde recogían la arena resultó ser donde se vertía y quemaba el plástico local&mdash; así que improvisaron, empacando una mezcla de arena y plástico en las botellas. Funcionó igual de bien, así que añadieron cada vez más plástico. Con una mezcla de botellas&mdash; algunas llenas de arena, otras llenas únicamente de plástico&mdash; construyeron un pequeño muro de jardín. Las botellas llenas de plástico no solo eran igual de efectivas, sino que tenían el beneficio adicional de asegurar plástico que de otro modo habría terminado en el río.',
    '021-block1-p1': 'Russell continuó el experimento en casa, construyendo su jardín con ellas. Sus vecinos querían saber más, así que trabajó con la escuela del pueblo para limpiar una vieja pila de plástico. La noticia se difundió rápidamente, y la idea fue recibida con entusiasmo abrumador&mdash; primero en su pueblo, luego en pueblos vecinos. A medida que la gestión de residuos plásticos alcanzaba un punto crítico en Bontoc, la capital provincial, creció la demanda de una solución accesible. Russell e Irene Bakisan desarrollaron la primera Guía Vision Ecobrick&mdash; un recurso sencillo y fotocopiable distribuido a cientos de escuelas. Para 2014, casi tres mil escuelas habían implementado el programa de ecoladrillos en todo el Departamento de Educación del norte de Filipinas.',
    '032-block1-video1-caption': 'Solving Plastic -- one bottle at a time in the Northern Philippines',
    '022-block1-p2': 'El desarrollo de los conceptos de ecoladrillo estuvo profundamente influenciado por los principios Igorot. Inspirados por un muro de piedra en terrazas de arroz que se había derrumbado en una tormenta y fue reconstruido usando las mismas piedras, Russell e Irene estaban decididos a que las construcciones de ecoladrillos también fueran reutilizables una y otra vez. Inspirados por el concepto de <a data-lang-id="023-block1-link1" href="/ayyew">Ayyew</a>, el equipo priorizó el uso de ecoladrillos para construir espacios verdes que enriquecieran vecindarios y escuelas.',
    '023-block1-link1': 'Ayyew',
    '024-block1-p3': 'Con el lanzamiento de <a href="index.php">Ecobricks.org</a> en 2013, el movimiento filipino de ecoladrillos descubrió que personas alrededor del mundo&mdash; desesperadas por una solución sencilla para el plástico&mdash; habían comenzado a ecoladrillar de forma independiente. Tras contactar con líderes del movimiento en Sudáfrica y Norteamérica y Centroamérica, se decidió formar una alianza para establecer consistencia en el creciente movimiento global. Encabezada por Russell Maier, Jo Stodgel (Upcycle Santa Fe), Candice Mostert, Patricia Acuna e Irene Bakisan, la Alianza Global de Ecoladrillos (AGE) se formó junto con la Guía Vision Ecobrick v2.0. En 2014, con el apoyo de Ian Domisse, fundador del Ecobrick Exchange en Sudáfrica, la alianza acordó usar el término sin guion y en minúsculas <b>&ldquo;ecobrick&rdquo;</b> como término estandarizado en todos los materiales&mdash; para que los ecoladrilladores de todo el mundo pudieran unirse en torno a una sola palabra, un hashtag y un término de búsqueda.',
    '033-block1-video2-caption': 'Seni Mengolah Sampah Plastik &ndash; Insight with Desi Anwar',
    '025-block1-p4': 'A principios de 2015, Russell se mudó a Indonesia y, con la ayuda de Nurkinanti Laraskusuma, la Guía Vision Ecobrick fue traducida al indonesio. A finales de 2015, Russell Maier y Ani Himawati fundaron oficialmente la AGE como una Empresa Terrestre sin fines de lucro, con la misión de apoyar la infraestructura tecnológica y filosófica del movimiento global de ecoladrillos. En 2016, el movimiento se encendió en Yogyakarta, Indonesia. Ani Himawati fue fundamental en el desarrollo de la metodología de capacitación de la AGE, aplicando <a data-lang-id="025a-block1-link1" href="https://russs.net/mandalas/" target="_blank" rel="noopener">los principios de manifestación comunitaria mandálica desarrollados por Russell Maier</a>&mdash; una metodología que desde entonces ha llevado al movimiento indonesio a un crecimiento exponencial a través de talleres iniciales, programas de formación de formadores y convergencias de ecoladrillos.',
    '025a-block1-link1': 'los principios de manifestación comunitaria mandálica desarrollados por Russell Maier',
    '034-block1-p9': 'En los años siguientes, el movimiento indonesio de ecoladrillos, en alianza con diversos gobiernos locales, organizaciones cristianas e islámicas, movimientos scout nacionales y movimientos ecológicos estudiantiles, ha sido dado a conocer a decenas de millones de indonesios a lo largo del archipiélago del país.',
    '026-block1-p5': 'El movimiento de ecoladrillos en el Reino Unido se encendió poco después de la emisión de Blue Planet II en diciembre de 2017. En enero de 2018, Mary Bacoo y Lucie Mann se unieron a la AGE como entrenadoras del Reino Unido. Lucie inició la página de Facebook Ecobricks UK, que despegó en octubre de 2018 cuando escándalos simultáneos en la industria del reciclaje del Reino Unido salieron a la luz y volvieron viral el ecoladrillado. Para 2019 había más de 30 Entrenadores de la AGE en el Reino Unido, y el movimiento involucraba a cientos de miles de ecoladrilladores.',
    '027-block1-quote1': '<i>&ldquo;No entendemos cómo sucede, pero con Blue Planet II, de repente el mundo se electrizó por el crimen de arrojar plástico al océano.&rdquo;</i>',
    '028-block1-quote1-citation': '&mdash; David Attenborough',
    '029-block1-p6': 'Durante 2017&ndash;18, cientos de entrenadores se unieron a la red de la AGE en Filipinas, Indonesia y Sudáfrica a través de nuestros <a data-lang-id="029a-block1-link1" href="/trainings">programas de formación de formadores</a> presenciales y en línea. En 2018, nuestros primeros tres entrenadores de EE.UU.&mdash; Sabrina Auclair, Luke Henkel y Jess Beck&mdash; se unieron al equipo.',
    '029a-block1-link1': 'programas de formación de formadores',
    '030-block1-p7': 'A finales de 2019, la atención mundial pasó de los peligros del plástico a los peligros del COVID-19. El ecoladrillado experimentó una disminución de la participación en todo el mundo.',
    '031-block1-p8': 'Sin embargo, el plástico no ha desaparecido. Todo lo contrario. El consumo de plástico y su descarga en los ecosistemas locales se ha acelerado en los últimos años. Lenta pero constantemente, un resurgimiento del ecoladrillado se está extendiendo de nuevo a medida que las comunidades se dan cuenta de que la gestión industrial y corporativa del plástico causa más problemas de los que resuelve.'

}
