/*-----------------------------------

INDONESIAN SNIPPETS FOR ECOBRICKS.ORG -- story.php


-----------------------------------*/


// Ampersand (&): Should be escaped as &amp; because it starts HTML character references.
// Less-than (<): Should be escaped as &lt; because it starts an HTML tag.
// Greater-than (>): Should be escaped as &gt; because it ends an HTML tag.
// Double quote ("): Should be escaped as &quot; when inside attribute values.
// Single quote/apostrophe ('): Should be escaped as &#39; or &apos; when inside attribute values.
// Backslash (\): Should be escaped as \\ in JavaScript strings to prevent ending the string prematurely.
// Forward slash (/): Should be escaped as \/ in </script> tags to prevent prematurely closing a script.


const id_Page_Translations = {

    '001-splash-title': 'Kisah Kami',
    '002-splash-subtitle': 'Aliansi Ecobrick Global berakar dari tanah dan tradisi kebijaksanaan masyarakat Igorot di Luzon Utara',
    '003-splash-image-alt': '<img alt="Komunitas ecobrick global" src="../pngs/community.png" style="width: 85%"/>',
    '005-first-page-paragraph': 'GEA lahir di lembah hijau Sungai Chico, di wilayah adat masyarakat Igorot (<i>Kaigorotan</i>) di Cordillera, Filipina Utara. Dipandu oleh etos <a href="/ayyew">Ayyew</a> dan prinsip-prinsip regeneratif mereka, kami menjadi yakin bahwa penyelesaian masalah plastik yang sesungguhnya memerlukan hubungan baru yang berhati-hati dengan ekonomi petro-kapital. Karena itu kami mendirikan GEA sebagai <a href="about.php#block2">Perusahaan Bumi</a> nirlaba&mdash; bebas untuk menjaga standar global bagi ecobricking dan sekuestrasi plastik tanpa motif keuntungan, dan sepenuhnya berfokus pada pelayanan bagi Bumi.',
    '007-gea-intro-image-alt': 'Logo mandalik Aliansi Ecobrick Global',
    '007-gea-intro-text': 'Aliansi Ecobrick Global telah berfokus pada transisi plastik selama lebih dari satu dekade. Kami melakukannya melalui penyebaran mandalik ecobricking yang berprinsip dan praktis untuk meningkatkan kesadaran ekologis.',
    '007-gea-intro-btn': 'Tentang GEA',
    '008-block1-header': 'Kisah Epik Asal Usul Kami',
    '009-block1-subheader': 'Bagaimana seorang pelancong yang terdampar, sebuah sungai, dan sebuah komunitas pegunungan memicu gerakan global.',
    '010-block1-hero-image-alt': 'Sawah bertingkat di Luzon Utara',
    '011-block1-hero-caption': 'Sawah bertingkat di Luzon Utara telah dijaga oleh masyarakat Igorot selama berabad-abad sebagai sarana swasembada pangan.',
    '012-block1-main2-p1': 'Aliansi Ecobrick Global berakar dari pegunungan di pelosok Filipina Utara. Pada tahun 2010, dalam sebuah liburan yang berujung buruk, <a href="https://www.spot.ph/newsfeatures/newsfeatures-peopleparties/71089/interview-russel-maier-ecobricks-a00171-20170810-lfrm2" target="_blank" rel="noopener">seniman asal Kanada Russell Maier terdampar di sebuah desa kecil di Lembah Sabangan</a>, di tanah masyarakat Igorot. Tidak mampu memenuhi kebutuhan hidup dan pulang, Russell&mdash; seorang seniman dengan latar belakang filsafat&mdash; <a data-lang-id="012a-block1-link1" href="https://russs.net/how-i-fucked-up-my-life-and-became-stranded-in-a-remote-tribal-village-for-four-years/" target="_blank" rel="noopener">terpaksa menjadikan Cordillera sebagai rumahnya selama lima tahun</a>.',
    '012a-block1-link1': 'terpaksa menjadikan Cordillera sebagai rumahnya selama lima tahun',
    '013-block1-main2-p2': 'Tinggal di komunitas itu, ia mulai bertanya-tanya apa yang terjadi pada botol plastik, kemasan, dan barang-barang lain yang ia konsumsi dan buang. Dengan mengikuti para tetangganya yang mengumpulkan dan membawa pergi sampah lingkungan, ia menemukan bahwa plastiknya dibuang ke Sungai Chico setempat, tempat anak-anak berenang dan para pria memancing. Terganggu oleh hal ini, ia mulai bereksperimen dengan daur ulang kreatif&mdash; memperbarui rumahnya dengan kreasi plastik dan menjualnya ke luar negeri. Namun ia terus dihantui satu pertanyaan: apa yang terjadi ketika kreasi plastik ini mencapai akhir masa pakainya? Apakah masalah plastik benar-benar terselesaikan?',
    '018-block1-main3-p1': 'Sekitar waktu itu, Russell diperkenalkan pada karya Andreas Froese, yang telah mengisi botol dengan pasir di Amerika Tengah untuk membuat &ldquo;bottle bricks&rdquo;. Russell dan teman-temannya pergi ke Sungai Chico untuk mencoba teknik tersebut. Tempat mereka mengambil pasir kebetulan berada di dekat lokasi pembuangan dan pembakaran plastik setempat&mdash; jadi mereka berimprovisasi dengan memasukkan campuran pasir dan plastik ke dalam botol. Cara ini ternyata sama efektifnya, sehingga mereka menambahkan semakin banyak plastik. Dengan campuran botol&mdash; sebagian diisi pasir, sebagian lagi hanya diisi plastik&mdash; mereka membangun dinding taman kecil. Botol berisi plastik ini tak hanya sama efektifnya, tetapi juga memberi manfaat tambahan yaitu mengamankan plastik yang jika tidak akan hanyut ke sungai.',
    '021-block1-p1': 'Russell melanjutkan eksperimen ini di rumah, membangun tamannya dengan botol-botol tersebut. Para tetangganya ingin tahu lebih banyak, sehingga ia bekerja sama dengan sekolah setempat untuk membersihkan tumpukan plastik lama. Kabar ini menyebar dengan cepat, dan gagasan ini disambut dengan antusiasme luar biasa&mdash; pertama di kota mereka, lalu ke kota-kota tetangga. Ketika pengelolaan sampah plastik mencapai titik krisis di Bontoc, ibu kota provinsi, permintaan akan solusi yang mudah diakses pun meningkat. Russell dan Irene Bakisan mengembangkan Buku Panduan Vision Ecobrick pertama&mdash; sumber daya sederhana yang bisa difotokopi dan dibagikan ke ratusan sekolah. Pada tahun 2014, hampir tiga ribu sekolah telah menerapkan program ecobrick di seluruh Departemen Pendidikan Filipina Utara.',
    '032-block1-video1-caption': 'Solving Plastic -- one bottle at a time in the Northern Philippines',
    '022-block1-p2': 'Perkembangan konsep ecobrick sangat dipengaruhi oleh prinsip-prinsip masyarakat Igorot. Terinspirasi oleh dinding terasering batu yang runtuh akibat badai dan dibangun kembali menggunakan batu-batu yang sama, Russell dan Irene bertekad agar konstruksi ecobrick juga dapat digunakan kembali berulang kali. Terinspirasi oleh konsep <a data-lang-id="023-block1-link1" href="/ayyew">Ayyew</a>, tim ini memprioritaskan penggunaan ecobrick untuk membangun ruang hijau yang memperkaya lingkungan dan sekolah.',
    '023-block1-link1': 'Ayyew',
    '024-block1-p3': 'Dengan diluncurkannya <a href="index.php">Ecobricks.org</a> pada tahun 2013, gerakan ecobrick Filipina menemukan bahwa orang-orang di seluruh dunia&mdash; yang putus asa mencari solusi sederhana untuk plastik&mdash; telah mulai melakukan ecobricking secara mandiri. Setelah menjalin kontak dengan para pemimpin gerakan di Afrika Selatan serta Amerika Utara dan Tengah, diputuskan untuk membentuk sebuah aliansi guna membangun keselarasan di seluruh gerakan global yang terus berkembang ini. Dipelopori oleh Russell Maier, Jo Stodgel (Upcycle Santa Fe), Candice Mostert, Patricia Acuna, dan Irene Bakisan, Aliansi Ecobrick Global (GEA) terbentuk bersamaan dengan Buku Panduan Vision Ecobrick v2.0. Pada tahun 2014, dengan dukungan Ian Domisse, pendiri Ecobrick Exchange di Afrika Selatan, aliansi ini sepakat menggunakan istilah tanpa tanda hubung dan huruf kecil <b>&ldquo;ecobrick&rdquo;</b> sebagai istilah baku di semua materi&mdash; sehingga para ecobricker di mana pun dapat bersatu dalam satu kata, satu tagar, dan satu kata kunci pencarian.',
    '033-block1-video2-caption': 'Seni Mengolah Sampah Plastik &ndash; Insight with Desi Anwar',
    '025-block1-p4': 'Pada awal 2015, Russell pindah ke Indonesia, dan dengan bantuan Nurkinanti Laraskusuma, Panduan Vision Ecobrick diterjemahkan ke dalam bahasa Indonesia. Pada akhir 2015, Russell Maier dan Ani Himawati secara resmi mendirikan GEA sebagai Perusahaan Bumi nirlaba, dengan misi mendukung infrastruktur teknologi dan filosofis gerakan ecobrick global. <a data-lang-id="025c-block1-link3" href="http://jogjatv.tv/pemkot-luncurkan-ecobricks-untuk-atasi-sampah-plastik/" target="_blank" rel="noopener">Pada tahun 2016,</a> gerakan ini <a data-lang-id="025b-block1-link2" href="https://www.youtube.com/watch?v=fK-cc8SfSW8" target="_blank" rel="noopener">menyala di Yogyakarta, Indonesia</a>. Ani Himawati berperan penting dalam mengembangkan metodologi pelatihan GEA, menerapkan <a data-lang-id="025a-block1-link1" href="https://russs.net/mandalas/" target="_blank" rel="noopener">prinsip-prinsip manifestasi komunitas mandalik yang dikembangkan oleh Russell Maier</a>&mdash; sebuah metodologi yang sejak itu membawa gerakan Indonesia tumbuh secara eksponensial melalui lokakarya pemula, program pelatihan pelatih, dan konvergensi ecobrick.',
    '025b-block1-link2': 'menyala di Yogyakarta, Indonesia',
    '025c-block1-link3': 'Pada tahun 2016,',
    '025a-block1-link1': 'prinsip-prinsip manifestasi komunitas mandalik yang dikembangkan oleh Russell Maier',
    '034-block1-p9': 'Sejak saat itu, gerakan ecobrick Indonesia, dengan menggandeng berbagai pemerintah daerah, organisasi Gereja dan Islam, gerakan pramuka nasional, serta gerakan ekologis pelajar, telah diperkenalkan kepada puluhan juta masyarakat Indonesia di seluruh penjuru nusantara.',
    '026-block1-p5': 'Gerakan ecobrick di Inggris menyala tak lama setelah tayangnya Blue Planet II pada Desember 2017. Pada Januari 2018, Mary Bacoo dan Lucie Mann bergabung dengan GEA sebagai pelatih dari Inggris. Lucie memulai <a data-lang-id="026a-block1-link1" href="https://www.facebook.com/groups/ecobricksUK" target="_blank" rel="noopener">halaman Facebook Ecobricks UK</a>, yang meledak popularitasnya pada Oktober 2018 seiring skandal-skandal dalam industri daur ulang Inggris yang mencuat di berita dan membuat ecobricking menjadi viral. Pada tahun 2019, jumlah Pelatih GEA di Inggris telah melampaui 30 orang, dan gerakan ini melibatkan ratusan ribu ecobricker.',
    '027-block1-quote1': '<i>&ldquo;Kami tidak mengerti bagaimana hal itu terjadi, tetapi dengan Blue Planet II, tiba-tiba dunia tersengat kesadaran akan kejahatan membuang plastik ke laut.&rdquo;</i>',
    '028-block1-quote1-citation': '&mdash; David Attenborough',
    '029-block1-p6': 'Sepanjang 2017&ndash;18, ratusan pelatih bergabung dengan jaringan GEA di Filipina, Indonesia, dan Afrika Selatan melalui <a data-lang-id="029a-block1-link1" href="/trainings">program pelatihan pelatih</a> kami, baik secara langsung maupun daring. Pada tahun 2018, tiga pelatih pertama kami dari AS&mdash; Sabrina Auclair, Luke Henkel, dan Jess Beck&mdash; bergabung dengan tim.',
    '026a-block1-link1': 'halaman Facebook Ecobricks UK',
    '029a-block1-link1': 'program pelatihan pelatih',
    '030-block1-p7': 'Pada akhir 2019, perhatian dunia beralih dari bahaya plastik ke bahaya COVID-19. Partisipasi ecobricking menurun di seluruh dunia.',
    '031-block1-p8': 'Namun, plastik tidak lantas menghilang. Justru sebaliknya. Konsumsi plastik dan pembuangannya ke ekosistem lokal semakin meningkat dalam beberapa tahun terakhir. Perlahan namun pasti, kebangkitan kembali ecobricking mulai menyebar seiring semakin banyak komunitas yang menyadari bahwa pengelolaan plastik oleh industri dan korporasi justru menimbulkan lebih banyak masalah daripada solusi.'

}
