<!DOCTYPE html>
<HTML lang="fr"> 
<HEAD>
<META charset="UTF-8">
<?php $lang='fr';?>
<?php $version='1.6';?>
<?php $page='brikcoins';?>

<?php require_once ("../includes/brikcoins2-inc.php");?>

<!--Once translation is completed, you can remove the line below to take the translation notice off the page-->


<!--PAGE BANNER-->


<div id="splash-content-block">
	<div id="splash-box">
		<div class="splash-heading" data-lang-id="001-splash-title">Brikcoins</div>
		<div class="splash-sub" data-lang-id="002-splash-subtitle">A manual proof-of-value blockchain based on the sequestration of plastic from the biosphere.</div>
		<img src="../webp/brikcoins-450px.webp" alt="Brikcoin manual blockchain">
	</div>
</div>
<div id="splash-bar"></div>

<!-- PAGE CONTENT-->

<div id="top"></div>
<div id="main-content">
<!-- The flexible grid (content) -->
	<div class="row">
		<div class="main">

			<div class="lead-page-paragraph">				
			<p>Based on real world ecological value, the Brikcoin manual-blockchain energizes our petro-capital transition to a regenerative world.</p>
			</div>

			<div class="page-paragraph">
		
				<p>Brikcoins (BRK / ß) are generated by human work and based on ecological value.</p>

				<p>More than just numbers in ledger, every brikcoin correlates directly with plastic that has been secured from from polluting the biosphere— and permanently removed from high-emissions industries. In the same way that ancient gold and silver coins have a value in and of themselves, Brikcoins are based on the ecological value that they represent.</p>

				<p>We call this a <i>proof-of-value, manual manual-blockchain.</i></p>
			

			</div>

			
			<div id="ECO-VALUE"></div>
			<div class="reg-content-block" id="block1">

				<div class="opener-header">
					
					<div class="opener-header-text">
					<h4>Ecological Value</h4>
					<h5>In following the Earth's example of carbon concentration we can generate authentic ecological and utility value.</h5>   
					<br>
					</div>

					<button onclick="preclosed1()" class="block-toggle" id="block-toggle-show1">+</button>
				</div>

				<div id="preclosed1">

				<div class="row">
						<div class="main2">

						<p>Two billion years ago, Earth's atmosphere was full of carbon dioxide.  The planet's climate was unstable and its surface barren.  However, steadily the atmosphere's CO2 was cycled into carbon-based life, which, generation after fallen generation, was buried and secured into the ground.  As more and more <a href="/plastic">carbon ended up sequestered</a>, there was less and less CO2 in the atmosphere.  Steadily the climate stabilized and Earth's biosphere blossomed.</p>

						</div>
						<div class="side2"><img src="../webp/earth-floating-500px.webp" style="width:100%" loading="lazy" alt="Earth service">
						</div>
					</div>
					<div class="row2">
						<div class="main3">
						<p>Today, our petroleum based plastic comes directly from these ancient underground carbon stores.  As a form of carbon, what we do with our plastic can be of ecological benefit— <i>or not</i>.</p>
						</div>
						<div class="side3"><img src="../pngs/albatross-blue-sky.gif" width="150" loading="lazy" alt="Earth service">
						</div>
					</div>
						

						<p>When plastic is dumped, it degrades into dangerous micro-plastics.  When plastic is incinerated it returns to the atmosphere as CO2.  And when plastic that is processed by industry it causes factories to spin and churn, resulting in more emissions and more plastic products.</p>
						
						<p>However, by following Earth's example of securing, concentrating and sequestring our cabon we can keep our plastic out of the biosphere and out of industry.  This work has important ecological value in so far as it avoids pollution, desperses benefit and supports biodiversity.</p>
						
						<p>This process of <a href="sequest">plastic sequestration</a> is defined as a manual, net-zero, non-industrial process (see the <a href="https://en.wikipedia.org/wiki/Plastic_sequestration" target="_blank">wikipedia page</a>).  In order to be sequestered, the resulting secured-plastic must meet the criteria of plastic sequestration to ensure that it is in fact green.</p> 

						<p>One of the most universal and accessible means of plastic sequestration is <a href="what.php">ecobricking</a>.</p>
						
						<p>Ecobricked plastic, <i>if it has been authenticated to have met the criteria of plastic sequestration</i>, embodies an ecological and utility value.  This value can be quantified by the weight of the plastic sequestered within it.</p>

						<p>Brikcoins are based on the ecological value of <a href="/aes">Authenticated Ecobrick Sequestered plastic (AES plastic)</a>.</p>

						<br><br>
						<hr>
						<h4>Learn More</h4>
						<h5>ℹ️ Wikipedia article: <a href="https://en.wikipedia.org/wiki/Plastic_sequestration" target="_blank" >Plastic Sequestration.</a></h5>
						
						<h5>ℹ️ <a href="sequest.php">The GEA's criteria for plastic sequestration.</a></h5>

						<h5>ℹ️ <a href="/plastic">The Long Story of Plastic.</a></h5>

						<h5>ℹ️ More on: <a href="/aes">AES Plastic.</a></h5>

					<h5>ℹ️ The theory of <a href="https://book.earthen.io" target="_blank">Earthen Ethics</a> of following Earth's example.</h5>
				
				</div>
			</div>


			<div id="PROOF-OF-VALUE"></div>
			<div class="reg-content-block" id="block2">

				<div class="opener-header">
					
					<div class="opener-header-text">
						<h4>Proof of Value</h4>
						<h5>Brikcoins are generated through the manual process of authenticating ecobrick sequestered plastic.</h5>   
						<br>
					</div>

					<button onclick="preclosed2()" class="block-toggle" id="block-toggle-show2">+</button>
				</div>

				<div id="preclosed2">

					<div class="row">
						<div class="main2">
							<p>Brikcoins are based on the ecological value of <a href="https://en.wikipedia.org/wiki/Plastic_sequestration" target="_blank" >sequestered plastic</a>— a concept which is based on following <a href="/plastic">Earth's example</a> of carbon care (the principles of <a href="https://earthen.io/imagine">Earthen ethics</a>).  Ecobricked plastic, in order to be considered sequestered must meet the <a href="sequest">criteria of plastic sequestration</a> developed by the <a href="about.php">Global Ecobrick Alliance.</a>  </p>
							
							<p>The final criteria of plastic sequestration, is that of <a href="sequest.php/#auth">independent authentication:</a> confirmation that that all the other criteria have been met.  In order to authenticate ecobricks that have been made around the world as sequestered plastic, the GEA maintains the <a href="/gobrik">GoBrik platform</a>.  There every ecobrick logged is peer reviewed by the ecobricker community to confirm whether it meets <a href="what.php">GEA ecobrick standards</a>.</p>

						</div>
						<div class="side2"><img src="../pngs/authenticated-ecobrick.png" style="width:100%" alt="authenticated ecobrick">
						</div>
					</div>
					<div class="row">
						<div class="main2">
						
						<p>Only when the peer review of an ecobrick is successful, is the plastic within it deemed have been sequestered.  This fulfils the final criteria of plastic sequestration (authentication), thereby both validating and finalizing the ecobrick's ecological value.  The brikcoins that represent this value are then generated in a block on the <a href="brikchain.php">brikchain</a>.</p>
									
						</div>
						<div class="side2"><img src="../webp/2-brikcoins-450px.webp" width="90%">
						</div>
					</div>		
					
					
					<div class="row2">
						<div class="main3">

						
						
						<p>In this way, Brikcoins avoid another pitfall of other blockhain currencies.  Rather than favor those who have capital to invest, as a non-capital, manual and community powered process, brikcoins favors those willing to work with their hands to make a meaningful ecological contribution regardless of their wealth or location.</p>
						</div>

						<div class="side3"><img src="../pngs/authenticated-ecobrick.png" width="150px">
					</div>
					</div>
				</div>
			</div>
			

			<div id="HOW"></div>
			<div class="reg-content-block" id="block3">

				<div class="opener-header">
					
					<div class="opener-header-text">
					<h4>How it works</h4>
					<h5>Brikcoins are generated and verified by human labour.</h5>   
					<br>
					</div>

					<button onclick="preclosed3()" class="block-toggle" id="block-toggle-show3">+</button>
				</div>

				<div id="preclosed3">

					<br>
					<img src="../pngs/manual-blockchain.png" width="100%" loading="lazy" alt="manual proof of value block chain">

					

					<p><b>Step 1: Ecobricking</b></p>

					<p>The brikcoin manual-blockchain revolves around the ecobricking of used plastic.  <a href="what">Ecobricking</a> is an established means of securing plastic. It is a time-consuming, labor-intensive process that is most effectively done manually.  If done <a href="/how">properly</a> an ecobrick can be used for long-term <a href="build">building applications</a>; ensuring that its plastic is secured from industrial processing and release into the biosphere.</p>

					<p>Once complete, ecobrickers log their ecobrick on the <a href="/gobrik">GoBrik</a> platform.  A serial number is given by the system and the ecobrickers enscribes this permanently on the ecobrick. A photo of the ecobrick with the serial number is taken and the logging completed.<p>
					
					<p>The logged ecobrick is then automatically queued for review.  The ecobricker is awarded credits that allow them to validate other ecobricks that have been logged.</p>

					<br><br>
					<p><b>Step 2: Validation</b></p>

					<p>The GEA has defined standards for an ecobrick. Only when a packed bottle meets these standards is it considered an ecobrick, and only then is the plastic it contains considered sequestered.</p> 

					<p>Using one validation credit, ecobrickers are entitled to validate one ecobrick from the queue. The validator proceeds through a three step process of reviewing ecobrick, to ensure that it meets the criteria and standards of plastic sequestration. In total, each ecobrick is reviewed by three validators in the community.</p>
					
					<br><br>
					<p><b>Step 3: Authentication</b></p>

					<p>An algorithm calculates a validation score based on the review. The three validation scores are averaged and if the average exceeds the minimum threshold, the ecobrick is authenticated. Brikcoins are then generated and issued to the validators and the <a href="https://gobrik.com/#cr">GoBrik Central Reserve</a> based on the weight of the ecobrick.</p>

					<p>The amount of Brikcoins generated is a function of the weight of the authenticated ecobricked plastic.  This 'plastic standard' is pegged to a ratio of 1 BRK (ß) to 100g of AES plastic. For example, a 322g ecobrick will generate 3.22 ß, while a 0.41 kg ecobrick will generate 4.10 ß.  As the blockchain operates however, this valuation fluctuates.  See the live <a href="brikchain.php">Brikchain Explorer</a> for the latest valuation.</p>
					<br><br>

				</div>
			</div>

			<div id="CENTRALIZED"></div>
			<div class="reg-content-block" id="block4">

				<div class="opener-header">
					
					<div class="opener-header-text">
					<h4>Centralized Decentralization</h4>
					<h5>The Brikcoin manual-blockchain is presided over by the Global Ecobrick Alliance</h5>   
					<br>
					</div>

					<button onclick="preclosed4()" class="block-toggle" id="block-toggle-show4">+</button>
				</div>

				<div id="preclosed4">

					<div class="row">
						<div class="main2">

							<p>The brikcoin manual-blockchain is developed and maintained by the <a href="about">Global Ecobrick Alliance</a> in pursuit of its mission and vision of plastic transition. As a not-for profit Earth Enterprise, the GEA is guided by a mandate of achieving net-green ecological impacts and redistributing excess revenue back to the global ecobrick movement.</p>
						</div>
						
						<div class="side2">
							<img src="../webp/gea-logo-400px.webp" width="80%">
						</div>
					</div>
					
					<div class="row2">
						<div class="main3">
							<p>Through a combination of enterprise structure and server infrastructure, we aim to minimize our grey ecological impacts and maximize of our collective green impact.</p>
						</div>
						<div class="side3"><img src="../webp/gea-logo-400px.webp" width="130px">
						</div>
					</div>
								
					<p>The brikcoin manual-blockchain is permissioned, meaning that its ledger is centralized on GEA managed databases. This structure was elected to minimize the impact of the servers supporting the blockchain, while at the same time maximize the blockchain's empowerment of the decentralized global ecobrick movement.</p>
				</div>
			</div>

			


			<div id="WHITEPAPER"></div>

			<div class="reg-content-block" id="block5">

				<div class="opener-header">
					
					<div class="opener-header-text">
						<h4>White Paper</h4>
						<h5>The Commodification of Sequestered Plastic</h5>   
						<br>
					</div>

					<button onclick="preclosed5()" class="block-toggle" id="block-toggle-show5">+</button>

				</div>

				<div id="preclosed5">

					<div class="row">
						<div class="main2">

							<p>On Earth Day 2020, the GEA released version 1.0 of the <i>Ecobricks & Brikcoin Whitepaper, on The Commodification of Manually Sequestered Plastic</i>.  The 32 page document is the work of half a dozen contributors specializing in fields ranging from micro-plastic research, alternative currencies, philosophy, community development and database development.</p>

							<p>The white paper lays out the framework for basing the brikcoin currency on the ecological value of plastic sequestration.</p>

						</div>

						<div class="side2"><img src="../pngs/White-Paper-Icon2-400px.png" width="100%" alt="Ecobricks & Brikcoin Whitepaper, on The Commodification of Manually Sequestered Plastic">
						</div>

					</div>


					<div class="row2">
						
						<div class="main3">
							<p>📥 Download: <a href="https://nextcloud.ecobricks.org/index.php/s/fNNYjG7A3gxco9n" target="_blank">The Commodification of Sequestered Plastic</a></p><h5>📄 GEA White Paper | PDF | 2.1 MB</h5>
						</div>

						<div class="side3">
							<img src="../pngs/White-Paper-Icon2-400px.png" width="150px" alt="Ecobricks & Brikcoin Whitepaper, on The Commodification of Manually Sequestered Plastic">
						</div>
					</div>
					
					<p>The white paper is updated as of March 2022 to reflect three years of beta-usage by our 50,000 gobrik users, over 150,000 ecobricks and a pool of over 250,000 ß (as of March, 2022).</p><br>

				</div>
			</div>



			<div class="page-paragraph-reg">
					
					<div class="row">
				
						<div class="main2">
							<br><br>
							<h3>The Brikchain</h3>
						
							<p>The proof-of-value manual manual-blockchain that powers Brikcoins is affectionately know as the <a href="brikchain.php">the brikchain</a> it is the full ledger of transactions generated by the authentication of ecobricked plastic around on the world on the GoBrik platform.  GoBrik and the Brikchain are maintained and developed by the Global Ecobrick Alliance as a for-Earth, non-profit enterprise.</p>

							<p>As a non-capital, manual process, Brikcoins favors anyone anywhere willing to work with their hands to make a meaningful ecological contribution.</p>
							<br><br>
							<a class="action-btn-blue" href="brikchain.php">🔎 Browse the Brikchain</a>
							<p style="font-size: 0.85em; margin-top:20px;">The live chain of transactions and ecobricks.</p>
						
						</div>

						<div class="side2">
							<br><img src="../webp/brk-cascade.webp" width="90%" alt="brikcoins in action" loading="lazy">
						</div>
					</div>
			</div>
		</div>
	


		<div class="side">
		
			<?php include '../ecobricks_env.php';?> 
			<?php require_once ("side-modules/brikcoin-live-values.php");?>
			<?php 	$conn->close();?>
			
				
			<?php include 'side-modules/about-gea.php';?> 

			<?php include 'side-modules/for-earth.php';?> 


			<?php include 'side-modules/earthen-ethics-principles.php';?> 
			
		</div>

	</div>
</div>



	<!--FOOTER STARTS HERE-->

	<?php require_once ("../footer-2024.php");?>


<!-- CUSTOM PAGE SCRIPTS-->

<!-- This script is for pages that use the accordion content system-->
<script src="../accordion-scripts.js" defer></script>


</div>
</body>
</html>



